export const positionOptions = {
    basketball: [
        { value: 'PG', label: 'Point Guard' },
        { value: 'SG', label: 'Shooting Guard' },
        { value: 'SF', label: 'Small Forward' },
        { value: 'PF', label: 'Power Forward' },
        { value: 'C', label: 'Center' },
    ],
    football: [
        { value: 'GK', label: 'Goalkeeper' },
        { value: 'DF', label: 'Defender' },
        { value: 'MF', label: 'Midfielder' },
        { value: 'FW', label: 'Forward' },
    ],
    baseball: [
        { value: 'P', label: 'Pitcher' },
        { value: 'C', label: 'Catcher' },
        { value: '1B', label: 'First Base' },
        { value: '2B', label: 'Second Base' },
        { value: '3B', label: 'Third Base' },
        { value: 'SS', label: 'Shortstop' },
        { value: 'LF', label: 'Left Field' },
        { value: 'CF', label: 'Center Field' },
        { value: 'RF', label: 'Right Field' },
    ],
    hockey: [
        { value: 'C', label: 'Center' },
        { value: 'LW', label: 'Left Wing' },
        { value: 'RW', label: 'Right Wing' },
        { value: 'D', label: 'Defenseman' },
        { value: 'G', label: 'Goaltender' },
    ],
    americanFootball: [
        { value: 'QB', label: 'Quarterback' },
        { value: 'RB', label: 'Running Back' },
        { value: 'WR', label: 'Wide Receiver' },
        { value: 'TE', label: 'Tight End' },
        { value: 'OL', label: 'Offensive Line' },
        { value: 'DL', label: 'Defensive Line' },
        { value: 'LB', label: 'Linebacker' },
        { value: 'CB', label: 'Cornerback' },
        { value: 'S', label: 'Safety' },
        { value: 'K', label: 'Kicker' },
        { value: 'P', label: 'Punter' },
    ],
};