// Map statTypes to display names and abbreviations for UI
export const statDisplayMap = {
  // Basketball
  twoPointFGM: { label: '2PT FG', abbr: '2PT' },
  twoPointFGA: { label: '2PT FG Attempt', abbr: '2PTA' },
  threePointFGM: { label: '3PT FG', abbr: '3PT' },
  threePointFGA: { label: '3PT FG Attempt', abbr: '3PTA' },
  freeThrowM: { label: 'FT Made', abbr: 'FTM' },
  freeThrowA: { label: 'FT Attempt', abbr: 'FTA' },
  offensiveRebound: { label: 'Off Reb', abbr: 'ORB' },
  defensiveRebound: { label: 'Def Reb', abbr: 'DRB' },
  assist: { label: 'Assist', abbr: 'AST' },
  steal: { label: 'Steal', abbr: 'STL' },
  turnover: { label: 'Turnover', abbr: 'TO' },
  block: { label: 'Block', abbr: 'BLK' },
  blockedShotAttempt: { label: 'Blocked Shot Attempt', abbr: 'BLKA' },
  personalFoul: { label: 'Foul', abbr: 'PF' },
  teamFoul: { label: 'Team Foul', abbr: 'TF' },
  technicalFoul: { label: 'Tech Foul', abbr: 'TF' },
  flagrantFoul: { label: 'Flag Foul', abbr: 'FF' },
  drawnFoul: { label: 'Drawn Foul', abbr: 'DF' },

  // American Football
  passingYards: { label: 'Pass Yards', abbr: 'PY' },
  passingTDs: { label: 'Pass TDs', abbr: 'PTD' },
  interceptionsThrown: { label: 'INT Thrown', abbr: 'INT' },
  rushingYards: { label: 'Rush Yards', abbr: 'RY' },
  rushingTDs: { label: 'Rush TDs', abbr: 'RTD' },
  fumblesLost: { label: 'Fumbles Lost', abbr: 'FUM' },
  receptions: { label: 'Receptions', abbr: 'REC' },
  receivingYards: { label: 'Recv Yards', abbr: 'RECY' },
  receivingTDs: { label: 'Recv TDs', abbr: 'RECTD' },
  tackles: { label: 'Tackles', abbr: 'TCK' },
  sacks: { label: 'Sacks', abbr: 'SCK' },
  interceptionsCaught: { label: 'INTs Caught', abbr: 'INTC' },
  fieldGoalsMade: { label: 'FG Made', abbr: 'FGM' },
  fieldGoalsMissed: { label: 'FG Missed', abbr: 'FGX' },
  extraPointsMade: { label: 'XP Made', abbr: 'XPM' },
  punts: { label: 'Punts', abbr: 'PNT' },
  puntYards: { label: 'Punt Yards', abbr: 'PTY' },
  kickReturns: { label: 'Kick Returns', abbr: 'KR' },
  kickReturnYards: { label: 'KR Yards', abbr: 'KRY' },

  // Soccer (Football)
  goals: { label: 'Goals', abbr: 'G' },
  assists: { label: 'Assists', abbr: 'A' },
  shotsOnTarget: { label: 'Shots on Target', abbr: 'SOT' },
  shotsOffTarget: { label: 'Shots off Target', abbr: 'SOF' },
  passesCompleted: { label: 'Passes Completed', abbr: 'PC' },
  passesAttempted: { label: 'Passes Attempted', abbr: 'PA' },
  foulsCommitted: { label: 'Fouls', abbr: 'F' },
  yellowCards: { label: 'Yellow Cards', abbr: 'YC' },
  redCards: { label: 'Red Cards', abbr: 'RC' },
  saves: { label: 'Saves', abbr: 'SV' },
  offsides: { label: 'Offsides', abbr: 'OFF' },
  corners: { label: 'Corners', abbr: 'CK' },
  clearances: { label: 'Clearances', abbr: 'CLR' },

  // Hockey
  shots: { label: 'Shots', abbr: 'S' },
  hits: { label: 'Hits', abbr: 'H' },
  blockedShots: { label: 'Blocked Shots', abbr: 'BS' },
  faceoffsWon: { label: 'Faceoffs Won', abbr: 'FOW' },
  faceoffsLost: { label: 'Faceoffs Lost', abbr: 'FOL' },
  penaltyMinutes: { label: 'Penalty Minutes', abbr: 'PIM' },
  plusMinus: { label: '+/-', abbr: '+/-' },
  takeaways: { label: 'Takeaways', abbr: 'TK' },
  giveaways: { label: 'Giveaways', abbr: 'GV' },
  powerPlayGoals: { label: 'PP Goals', abbr: 'PPG' },
  shortHandedGoals: { label: 'SH Goals', abbr: 'SHG' },
  gameWinningGoals: { label: 'GW Goals', abbr: 'GWG' },
  goalsAgainst: { label: 'Goals Against', abbr: 'GA' },
  savePercentage: { label: 'Save %', abbr: 'SV%' },

  // Baseball
  atBats: { label: 'At Bats', abbr: 'AB' },
  runs: { label: 'Runs', abbr: 'R' },
  RBIs: { label: 'RBIs', abbr: 'RBI' },
  homeRuns: { label: 'HRs', abbr: 'HR' },
  doubles: { label: 'Doubles', abbr: '2B' },
  triples: { label: 'Triples', abbr: '3B' },
  walks: { label: 'Walks', abbr: 'BB' },
  strikeouts: { label: 'Strikeouts', abbr: 'K' },
  stolenBases: { label: 'Stolen Bases', abbr: 'SB' },
  caughtStealing: { label: 'Caught Stealing', abbr: 'CS' },
  inningsPitched: { label: 'Innings Pitched', abbr: 'IP' },
  earnedRuns: { label: 'Earned Runs', abbr: 'ER' },
  pitchesThrown: { label: 'Pitches Thrown', abbr: 'PIT' },
  strikesThrown: { label: 'Strikes Thrown', abbr: 'STR' },
  battersFaced: { label: 'Batters Faced', abbr: 'BF' },
  fieldingErrors: { label: 'Fielding Errors', abbr: 'E' },
};